---
driver:
  name: ${LSR_MOLECULE_DRIVER:-docker} 
  options:
    managed: false
    login_cmd_template: docker exec -ti {instance} bash
    ansible_connection_options:
      ansible_connection: community.docker.docker
      ansible_become_method: sudo         
dependency:
  name: galaxy
  options:
    role-file: meta/requirements.yml
    requirements-file: molecule/centos/requirements.yml
provisioner:
  name: ansible
  log: true
  env:
    ANSIBLE_BECOME: True
    ANSIBLE_BECOME_METHOD: sudo
    ANSIBLE_BECOME_USER: root     
    MOLECULE_EPHEMERAL_DIRECTORY:  /tmp/.molecule
  config_options:
    defaults:
      local_tmp: /tmp/.ansible-$USER/tmp
      remote_tmp: /tmp/.ansible-$USER/tmp
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
- name: "indra-${image:-centos}-${tag:-stream8}${TOX_ENVNAME}"
  image: "${namespace:-quay.io/centos}/${image:-centos}:${tag:-stream8}"
  command: /sbin/init
  privileged: true
  pre_build_image: true
scenario:
  name: ubuntu
  test_sequence:
    - syntax
    - destroy
    - create
    - dependency
    - prepare 
    - converge
    - idempotence
    - side_effect
    - verify
    - destroy 
