---
- name: Prepare
  hosts: all
  become: yes
  gather_facts: no
  tasks:
  - name: Test SystemD
    shell: systemctl status
    register: systemd_status
  - name: Mostrar estado de Systemd
    debug:
      msg: "{{ systemd_status.stdout }}"
  - name: List Repos
    ignore_errors: yes
    find:
      paths: /etc/yum.repos.d
      file_type: file
    register: found_repos
  - name: Fix Repos URL
    ignore_errors: yes
    replace:
        path: "{{ repo.path }}"
        regexp: "mirror.centos.org"
        replace: "vault.centos.org"
    loop: "{{ found_repos.files | default([]) }}"
    loop_control:
       loop_var: repo
  - name: Fix Repos baseurl
    ignore_errors: yes
    replace:
        path: "{{ repo.path }}"
        regexp: "#.*baseurl=http"
        replace: "baseurl=http"
    loop: "{{ found_repos.files | default([]) }}"
    loop_control:
       loop_var: repo
  - name: Fix Repos mirrorlist
    ignore_errors: yes
    replace:
        path: "{{ repo.path }}"
        regexp: "mirrorlist=http"
        replace: "##mirrorlist=http"
    loop: "{{ found_repos.files | default([]) }}"
    loop_control:
       loop_var: repo
  - name: Rebuild RPM Database
    ignore_errors: yes
    command: "rpm --rebuilddb"

- name: Prepare
  hosts: all
  become: yes
  gather_facts: yes
  vars:
     #########################################################
     #            APACHE SERVER CONFIGURATIONS
     #########################################################
     apache_user: "apache"
     apache_shell: "/bin/bash"
     apache_group: "{{ apache_user | default(apache)}}"
     apache_options: "All Indexes FollowSymLinks"
     # Los modulos pueden romper la instalacion, si las dependencias estan mal.
     #apache_mods_enabled:
     #    - rewrite
     #    - ssl
     #    - mpm_itk_module
     apache_mods_disabled: []

     #########################################################
     #            PHP CONFIGURATIONS FOR GRAV
     #########################################################
     #------------
     # 1.- Main Config
     #------------
     php_user:  "{{apache_user | default(apache) }}"
     php_group: "{{php_user    | default(apache) }}"
     php_install_from_source: false
     php_enable_webserver: true
     php_webserver_daemon: "httpd"
     php_packages_state: "present"
     php_install_recommends: true
     php_executable: "php"
     php_packages:
         - php
         - php-cli
         - php-common
         - php-devel
         - php-gd
         - php-mbstring
         - php-pdo
         - php-pecl-apcu
         - php-xml
         - php-curl
         - php-ctype
         - php-dom
         - php-gd
         - php-json
         - php-mbstring
         - php-openssl
         - php-session
         - php-simplexml
         - php-xml
         - php-zip

     #------------
     # 2.- PHP ini
     #-------------
     php_memory_limit: "128M"
     php_max_execution_time: "90"
     php_upload_max_filesize: "256M"

     #---------
     # 3.- OPT Cache
     #--------
     php_opcache_zend_extension: "opcache.so"
     php_opcache_enable: "1"
     php_opcache_enable_cli: "0"
     php_opcache_memory_consumption: "96"
     php_opcache_interned_strings_buffer: "16"
     php_opcache_max_accelerated_files: "4096"
     php_opcache_max_wasted_percentage: "5"
     php_opcache_validate_timestamps: "1"
     php_opcache_revalidate_path: "0"
     php_opcache_revalidate_freq: "2"
     php_opcache_max_file_size: "0"
  roles:
    - role: geerlingguy.apache
    - role: geerlingguy.php
